### ISSUE TITLE
No way to tell when a kb has been updated

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1034]
Originally by _[adeiana (@Osso)](https://github.com/Osso)_ on 2012-05-04

I am trying to use the datacacher for knowledgebases however I need to give it at timestamp if I want the kb to ever be refereshed.
The problem the timetstamp is stored nowhere currently

**Comment by jirikuncar** [comment]
KBs should not be cached per process. If *Flask-Cache* (Redis) is used the cache cleaning can be triggered by *SQLAlchemy* signal `after_model_updated` on KB tables.

**Comment by jirikuncar** [comment]
@kaplun is the caching still needed for any reason?

**Comment by Osso** [comment]
docextract iterates through all the entries of the journals abbreviations which about 11k entries. The problem comes from the time is takes to compile a regexp for each entry.

At the time, we looked at caching the compiled regexp (which is possible but a bit hackish) or using non regexp search (which may be best) but atm the regexp is cached in the process memory.

**Comment by jirikuncar** [comment]
Is `docextract` run as part of user request?

> 11k entries

This might be a problem for `re` module itself. There is IMHO a limit on some systems (e.g. OS X) on how big the normal regular expression can be.

**Comment by Osso** [comment]
It's 11k separate regexps.
There's a tool that runs it as part of user request indeed (but I forgot the url).

**Comment by jirikuncar** [comment]
> docextract iterates through all the entries

[esmre](https://pypi.python.org/pypi/esmre) might be useful here.

**Comment by Osso** [comment]
It's so cool!

**Comment by kaplun** [comment]
INSPIRE specific and superseded.
