### ISSUE TITLE
MultiEdit to support undo

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1043]
Originally on 2012-05-08

It would be great to have a way to revert a MultiEdit modification, i.e. to revert to the previous version all the records affected by one MultiEdit call.

For that we would require a place where to store the list of accted records.

**Comment by jirikuncar** [comment]
Invenio 3 provides powerful REST APIs for modifying records. Use OAuth tokens with correct scopes to get additional rights.

**Comment by tiborsimko** [comment]
@jirikuncar Note that the issue at hand here was not about additional record modification rights, but about having an easy "undo" button for cataloguers once they trigger a multi-record modification, in case they would like to revert it back later.

**Comment by jirikuncar** [comment]
Undo is solved in Invenio 3 via full record versioning.

**Comment by kaplun** [comment]
@jirikuncar, not for batch: i.e. when let's say 300 hundred records are modified via a single operation, there was (and there isn't) a way to easily revert those 300 records to their state before the modification. This is not a problem to be solved in `invenio-records`, but at the higher level of cataloguing tools (that's why MultiEdit was concerned).

**Comment by jirikuncar** [comment]
@kaplun There is a way. You can identify the transaction in SQLAlchemy-Continuum.

**Comment by tiborsimko** [comment]
@jirikuncar There may be a "developer way", but the original goal of this issue was to have a "cataloguer-ready undo" button" like functionality exposed in the MultiEdit interface.  In the Invenio 3 times, we basically just need to think of exposing nice "undo" APIs that can be later called by the future cataloguing tools. These tools need to be developed still, so it is indeed good for this ticket to remain closed :).  But the underlying topic, "exposing nice and documented undo APIs", should still be kept in mind for Invenio 3.
