### ISSUE TITLE
ISBN management

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1270]
Originally

**ISBNs** are the standard identifiers for books. They are a sequence of numbers with a checksum and a rule on how to put dashes among digits in order to group them.

See: http://www.isbn.org/standards/home/isbn/international/hyphenation-instructions.asp.

There are Python tools in order to correctly handle the hyphenation:
http://pypi.python.org/pypi/python-stdnum
http://code.google.com/p/isbnid/
http://pypi.python.org/pypi/isbn_hyphenate

```python
In [1]: from isbn_hyphenate import hyphenate as ihy

In [2]: ihy("9992158107")
Out[2]: '99921-58-10-7'

In [3]: ihy("8535902775")
Out[3]: '85-359-0277-5'

In [4]: ihy("097522980X")
Out[4]: '0-9752298-0-X'
```

ISBN should be correctly handled throughout Invenio, by:
* upon input, washing away the hyphenation, while checking the checksum:
* storing them in a standard way e.g.:
```
020 $a 0451450523
```
* correspondingly normalizing the ISBN term when searching:
```
isbn:"85-359-0277-5" -> isbn:"8535902775"
```
(see [#852](http://invenio-software.org/ticket/852#comment:4))
* formatting with hyphenation (using the above cited **isbn_hyphenate** library)

This task is hence made up of several subtasks:
1. Implementing an `isbnutils.py` in miscutils in order to include hyphenation, stripping, and checksumming.
2. Implementing a new `isbn:` special logical field in the search_engine.py in order to strip hyphens.
3. Implementing a `bfe_isbn.py` format element in order to perform online hyphenation. Additionally this could allow inter-linking to other records (see: #1185)

**Comment by tiborsimko** [comment]
Partially addressed via https://github.com/inveniosoftware/idutils.  If there is a need to plug it into various new standalone Invenio components, let's create new issues there.

**Comment by aw-bib** [comment]
@kaplun just noticed this issue and there are (unfortunatley) some points form the librarian.

- I perfectly agree with dehyphenation in searches and in the index.
- I fear your libs handle only _valid_ ISBNs. However, a lot of "formally invalid" ISBNs are around (e.g. wrong checknums etc.) This could quite a bit affect your re-hyphenation. Cf. [Library of Congress, 020](http://www.loc.gov/marc/bibliographic/bd020.html) and the section about "invalids".
- Re-hypenation can be quite an issue, as acutally IRL number groups overlap between small publishers and large publishers. So if you strip the hyphens for storage, IRL I think there is _no_ way to re-add them automagically and correctly in all cases. (Even if you treat formally valid ISBNs only). This was a real world problem for "potential dupe"-alerts in one of the univ. libraries I worked at. For me this would be a point like "if someone adds the hyphens keep them, but search and index without them". Plus: I'd not care to much about re-adding them if they are lost. Simply, as for the relevant cases the automatism fails anyway, and for the non-relevant case, well it's not relevant.
- Unlike a DOI that should be pointing to one article this is not the case for an ISBN. So I'd not really treat ISBNs as an ID as such. It's quite a bit "softer" than a real ID. You have a lot of cases where the same ISBN points to more than one book. Multi volume works are a very common case. Similarly subsequent editions, even if they incorporate major changes.

Due to the latter point I do not really know if it's worthwhile to put too much effort in this only half useful concept of _ISBN_. It works nicely for ordering a book that is currently available at the publisher. And only for them. All beyond (e.g. dupe checking and things) is probably asking way to much from this number. So I'd keep things simple and leave out all fancy libs.

I'm not sure how to ticketize those comments in idutils

**Comment by kaplun** [comment]
@aw-bib indeed one can simply strip dashes and friends upon searching and indexing, while rebuilding the dashes upon formatting (which would work only for valid ISBN. Invalid ones... too bad, they would be without dashes, I don't think it would do such a big harm).

> I'm not sure how to ticketize those comments in idutils

I think @lnielsen basically said similar in inveniosoftware/idutils#6.

**Comment by aw-bib** [comment]
>  while rebuilding the dashes upon formatting

I admit that I wouldn't even care about this either and just leave out the lib requirement. If it's entered with dashes they are there and stored. If not, well they are not. As long as search can handle both cases and as ISBN is not suitable for some persistent id anyway...

**Comment by kaplun** [comment]
As a user I do care. I really cannot read an ISBN without dashes. Instead when I nicely see a 978-... I immediately understand it's an ISBN even without seeing an ISBN label in front. It's a matter of usability :-)
