### ISSUE TITLE
RFC: deposit: multiuser submission

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#1946]
**Problem:**

Currently, deposit module is dependent on having a current user, and the data model is tied to a user id.

This prevents both:

- Guest submissions in the deposit module (~~needed by Inspire~~).
- Multiple users access to a single deposition (needed by Zenodo).

**Proposal:**

- Remove user id property from deposition model.
- Add model for controlling access to deposition (e.g. many-to-many relationship between a depositions and (users ~~or access tokens~~)).
- ~~Allow access to a deposition based on an access token (to support guest submissions). This allow long running guest submissions, and sharing a guest submission. Likely the access token should expire and deposition cleaned be up after a while.~~

Co-authored-by: @lnielsen-cern, @kneczaj @pedrogaudencio @giokokos

**Comment by lnielsen** [comment]
Closing this for now as no one are working on it. Eventually we will need on Zenodo and reopen then.

**Comment by tiborsimko** [comment]
In cases like this, we should also change the milestone for better book keeping.  E.g. we can use a latter milestone like "2.5" (if resources are planned), or use "someday" (if unknown).  Otherwise this issue would not be easily distinguishable from any regularly closed RFC for 2.2.

P.S. In the CERN Open Data project we use "someday" as a milestone, not as a label.  This seems more appropriate in this case for better bookkeeping.  Let's see IRL if we change it globally too.
