### ISSUE TITLE
WebSearch: do not display already deleted records in index proposal list

### ISSUE THREAD

**Issue by cplott** [inveniosoftware/invenio#2580]
We saw that a deleted record is dispayed in the proposal list after searching a similar term.

We searched, e.g., 7870_i:"IsParent" (http://juser.fz-juelich.de/search?ln=en&p=7870_i%3A%22IsParent%22) and got:
Search term IsParent inside index 7870_i did not match any record. Nearest terms in any collection are:
26 	  	IsMemberOf
- 	  	IsParent
1 	  	isPreprint

But the recod of "isPreprint" is already deleted! Should invenio really refer to such index entries?

**Comment by tiborsimko** [comment]
@cplott The collection is not being checked thoroughly when the list of nearest terms is generated, hence terms from records appearing in other collections might get displayed.  There are several possible solutions to consider, such as (1) post-filter only active records, or only public records, or only records permitted to the given user; (2) hard-delete your records, so that they would retain only 001 and 980 fields, then the old title would be empty and not indexed and would not appear in the list; or even (3) hide the nearest terms facility completely, as some sites have chosen.

**Comment by cplott** [comment]
Thanks for your feedback. We would prefer solution (1) post-filter only active records. Is this option already available in the settings? If it's not, is it possible to implement this option?

**Comment by tiborsimko** [comment]
@cplott It is not yet available, but it is relatively easy to implement.  One has to modify get_nearest_terms functions in order to exclude terms which have no hits outside deleted records collection.  This can be done via set intersection technique similarly to  
what `get_nearest_terms_in_idxphrase_with_collection()` already does.  Would you like to have a look?

**Comment by cplott** [comment]
OK, yes, I look into it.

**Comment by tiborsimko** [comment]
@cplott Have you managed to prepare a pull request for this issue? If so, please re-open it... I'm closing the issue for now as per the legacy code base freeze.

**Comment by cplott** [comment]
OK. Sorry, I didn't found the time for it.
