### ISSUE TITLE
Flask-Admin - jquery errors

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2690]
Hi guys,
I tried to use the admin interface but I received many errors.
E.g. if I go to the Role Admin page ( */admin/accrole/* ), firebug show me these errors:

```
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/vendor/select2/select2-bootstrap3.css"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/filters-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/form-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/filters-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/form-1.0.0.js"
"NetworkError: 404 NOT FOUND - http://0.0.0.0:8080/admin/js/actions-1.0.0.js"
ReferenceError: AdminModelActions is not defined
ReferenceError: jQuery is not defined
```

Something is gone wrong in my environment or also you have this problem? :)

**Comment by hachreak** [comment]
thanks @bouzlibop 
I run bower and now it has found the js, but I have problems with jquery (please see attached image).

![jquery-errors](https://cloud.githubusercontent.com/assets/377047/5835202/fc058df6-a165-11e4-9c66-39317d72354c.png)

**Comment by hachreak** [comment]
@lnielsen @bouzlibop  Have you some ideas how can be fixed this problem? :)
This problem seems to affect all the extra functionality of Flask-Admin (like filtering and deleting more than one) T_T

**Comment by bouzlibop** [comment]
Here's my 2 cents.

There are several problems happening:

1) Bundle with jQuery is being loaded to late - some views from `flask-admin` are trying to use it, before it actually arrives.
*Possible solution:* loading jQuery manually in `invenio/base/templates/admin_base.html`
```
{%- block _bottom_assets %}
    {{ super() }}
    <script src="{{ url_for('admin.static', filename='vendor/jquery-2.1.1.min.js') }}" type="text/javascript"></script>
{%- endblock _bottom_assets %}
```

2) ` Mismatched anonymous define() module: function (momentjs, $, exports) ...` - this happens because `datarangepicker.js` is using define (if available) to create module, but this script is called from regular src tag in `flask-admin` views rather then via RequireJS API, more on this here - http://requirejs.org/docs/errors.html#mismatch 
*Possible solution:* naming the module in  `vendor/bootstrap-daterangepicker/daterangepicker.js`
```
define("daterangepicker", ['moment', 'jquery', 'exports'], function(momentjs, $, exports) {
  root.daterangepicker = factory(root, exports, momentjs, $);
});
```

3)  `Uncaught TypeError: undefined is not a function` - it is because we are trying to call tooltip method defined in the `bootstrap.min.js` - which is at this point not available yet:
*Possible solution:* as we cannot change things in `flask-admin` and at the same time IMHO don't need this fancy tooltips, we can just mock this method in `invenio/base/templates/admin_base.html`
```
{%- block _bottom_assets %}
    {{ super() }}
    <script src="{{ url_for('admin.static', filename='vendor/jquery-2.1.1.min.js') }}" type="text/javascript"></script>
    <script>
        jQuery.fn.extend({
            tooltip: function () {
                }
        });
    </script>
    {% block tail %}{% endblock -%}
{%- endblock _bottom_assets %}
```

All of above are bigger or smaller hacks, but I hope these can give a hint for the ultimate solution :smile:

**Comment by jirikuncar** [comment]
> 1) Bundle with jQuery is being loaded to late

You can try to do similar trick we are doing for legacy templates (see `legacy_page_base.html`).
