### ISSUE TITLE
search: remove legacy webinterface

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#2958]
- [x] remove `invenio/legacy/websearch/webinterface.py`
- [x] check all imports
- [x] implement `/unapi` url handler (@tiborsimko is it used somewhere?)

**Comment by jmartinm** [comment]
will this be removed as well https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/formatter/engine.py#L519-L545 ??

Its quite horrible, for example, I am trying to create a brief record template and every time there is a Jinja exception instead of seeing the real error this fallback happens and some default Invenio template is being rendered :scream: 

Shall I create separate issue?
