### ISSUE TITLE
search: user-selectable date format

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#297]
Originally on 2010-09-23

Per conversation on inspire-dev related to #263, users with accounts should be able to set their preferred date format for search and display, e.g.:
dd/mm/yyyy vs. mm.dd.yyyy etc.

**Comment by jirikuncar** [comment]
@jalavik do we want to tackle this issue for 2.1?

**Comment by jalavik** [comment]
@jirikuncar Possibly, but not it may not make it depending on how many other issues pop up. 

On the subject of the issue, I feel that this is probably something can can be tailored to the users locale automatically, or?

**Comment by jirikuncar** [comment]
> I feel that this is probably something can can be tailored to the users locale automatically

I think so too. Plus *Babel* can help us here a lot.

--
Anyway, it has a minor priority so in case we don't have time we can postpone it.

**Comment by tiborsimko** [comment]
For Invenio 1.x we have `dateutils` that offers `convert_datetext_to_dategui` that offers this functionality for the *output* direction.  So it is just a matter to plug it into "wanted places".

However, the original issue was also about *input* direction, i.e. supporting this in the search syntax. This would mean that people could type things like "datecreated:yy/mm/dd" or "datecreated:dd.mm.yyyy" depending on their habits.  I think it would be very confusing to support this in the search engine "as is", since the same URL would give different results depending on from where it is called. Theoretically, this should not be treated via locale, but via user preferences.  Practically, however, even with user preferences this could be confusing when sharing links...  

I'd vote for using only one standard ISO date format in the search syntax and for closing this issue. If similar feature is needed on INSPIRE, one could consider implementing an intelligent search UI input box, e.g. JS that would read whatever user types and generate appropriate ISO date, etc. CC @kaplun

**Comment by kaplun** [comment]
> I'd vote for using only one standard ISO date format in the search syntax and for closing this issue. If similar feature is needed on INSPIRE, one could consider implementing an intelligent search UI input box, e.g. JS that would read whatever user types and generate appropriate ISO date, etc. CC @kaplun

:+1:

**Comment by jirikuncar** [comment]
### Conclusion

Use only standard ISO date format in the search syntax.
