### ISSUE TITLE
Issues with 0.0.0.0 and Chrome

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#3052]
The default site URL used in the developer setup is `0.0.0.0`. Recently, Chrome is not working so well with this URL prefix (http://stackoverflow.com/questions/28112933/how-to-stop-chrome-from-searching-when-manually-typing-in-local-dev-addresses). 

Even the [wikipedia entry](http://en.wikipedia.org/wiki/0.0.0.0) for this URL states:
> 0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown or non applicable target.

It's recommended to use `127.0.0.1` or `localhost` instead. Shall we change this default everywhere in the docs and elsewhere applicable?

**Comment by crepererum** [comment]
We should favour `localhost` over `127.0.0.1`, because it does not force IPv4. This simplifies testing and seems to be more future-proof (someday someone might have the idea to deactivate IPv4 handling for browser and other tools by default, because IPv4 addresses [can be fully mapped to IPv6 addresses](https://tools.ietf.org/html/rfc4291#page-10)).

**Comment by jacquerie** [comment]
The incorrect, but commonly expected, behavior for `0.0.0.0` is being readded to Chrome: https://chromium.googlesource.com/chromium/src/+/65e7a0403eb51c8490ee13e5da3ed8e544c34926. On the other hand, I support the idea of using `localhost` instead.

@crepererum I see a few other mentions of `0.0.0.0` in the codebase. What about these?
```shell
(invenio2)~/.virtualenvs/invenio2/src/invenio$ ag "0\.0\.0\.0"
INSTALL.rst
452:    (invenio)$ inveniomanage config set CFG_SITE_URL http://0.0.0.0:4000
453:    (invenio)$ inveniomanage config set CFG_SITE_SECURE_URL http://0.0.0.0:4000
522:     * Running on http://0.0.0.0:4000/
547:`http://0.0.0.0:4000/ <http://0.0.0.0:4000/>`_

docs/getting-started/overlay.rst
225:    (myoverlay)$ inveniomanage config set CFG_SITE_URL http://0.0.0.0:4000
226:    (myoverlay)$ inveniomanage config set CFG_SITE_SECURE_URL https://0.0.0.0:4000
588:    http = 0.0.0.0:4000

docker-compose.yml
22:  command: inveniomanage runserver -h 0.0.0.0 -p 5000

invenio/legacy/inveniocfg.py
829:    is 0.0.0.0, then use that, since we are running inside Docker.
838:    if '0.0.0.0' in cfg.get('CFG_SITE_URL'):
839:        return '0.0.0.0'

invenio/legacy/wsgi/__init__.py
262:                                                       '0.0.0.0'))  # not found

invenio/ext/elasticsearch/config/elasticsearch.yml
197:# ElasticSearch, by default, binds itself to the 0.0.0.0 address, and listens

docker-compose-dev.yml
22:  command: /code/scripts/docker_devboot.sh master inveniomanage runserver -h 0.0.0.0 -p 5000 -d -r
```

**Comment by crepererum** [comment]
@jacquerie `CFG_SITE_URL*` is the URL promoted by Invenio. You should usually set this one to a hostname. We tried to clarify this in the linked PR by adding a new config option for the binding address and port. These are not necessarily the same as the URL, because you might want to shield Invenio using a reverse proxy (e.g. Apache, HAProxy, NGINX, ...).

The docker things are an override for the docker specific setup, because here we must bind to all interfaces to make exposing of ports working. The `-h` flag only affects binding and not the URL generation (even if the log entry that flask emits on startup might suggest something different).

The legacy part is ... legacy. The part you are mentioning is used for Apache config generation. As far as I know it should be reworked anyway.

ElesticSearch: it is about binding, not about some URsL. It does not affect the frontend and is therefore unrelated.

For the Chrome part: I don't care, because the original argument that `0.0.0.0` is not a useful hostname is still valid and so we should change it. We should not make mistakes only because it is commonly accepted.

**Comment by jalavik** [comment]
@jacquerie Good to see that Chrome is adding the behavior back. Was driving me nuts.

I would still like to see the `INSTALL.rst` updated to suggest `localhost` as many devs would setup their initial environment using this - unless there was an issue I missed regarding `0.0.0.0` vs. `localhost`
