### ISSUE TITLE
account: make upgrade recipe accounts_2015_03_06_passlib safer

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#3070]
- [ ] use `db.String().with_variant(mysql.VARCHAR(255), 'mysql')` in https://github.com/inveniosoftware/invenio/blob/956f9c476273d506313a15fe49e62adcdaa2f70a/invenio/modules/accounts/upgrades/accounts_2015_03_06_passlib.py#L85
- [ ] ~~Shall we only rename the column to `old_password` in https://github.com/inveniosoftware/invenio/blob/956f9c476273d506313a15fe49e62adcdaa2f70a/invenio/modules/accounts/upgrades/accounts_2015_03_06_passlib.py#L81~~

--
cc @pbroz

**Comment by lnielsen** [comment]
Sorry, only had a very quick look, but what is the error or problem discovered?

E.g. ``password`` is hashed and stored into ``new_password``. Leaving ``old_password`` doesn't seem like a good idea to me (might be because I just don't know the underlying reason). I think it's better password be 255 chars since we don't have control of the hashing algorithm used by an Invenio instance.

**Comment by jirikuncar** [comment]
>  doesn't seem like a good idea to me

If the upgrade fails there is no quick rollback possible. (see email from @pbroz on mailing list)

**Comment by lnielsen** [comment]
Mailing list message:

Hello,

we have installed the current git master Invenio version over an older
one from pu (09/28/2014) but now no user is able to log in. The system
says "Invalid credentials".

We have managed to reset password for individual users through
inveniomanage shell but would like to warn other people of this
possibly serious problem.

We suspect accounts_2015_03_06_passlib upgrade recipe to be the
culprit. Since the upgrade recipe also deletes old passwords, there is
probable no way back.

Regards,

Petr

**Comment by lnielsen** [comment]
Perhaps related to empty passwords

**Comment by jirikuncar** [comment]
In reply to https://github.com/inveniosoftware/invenio/issues/3070#issuecomment-102351418: @lnielsen can we close it?

**Comment by lnielsen** [comment]
No, it's a real issue. Previous Invenio versions stored empty passwords as empty strings in the database instead of hashing them as every other value, so the upgrade recipe needs to take this into account.
