### ISSUE TITLE
Docker: building, non-existent files

### ISSUE THREAD

**Issue by lovasko** [inveniosoftware/invenio#3115]
This line https://github.com/inveniosoftware/invenio/blob/master/Dockerfile#L83 seems to be expecting a `git clone` of the invenio repository in the `/` directory inside the container. Is there some special way to build the Dockerfile apart from `docker build .`? If so, is it intentional that the basic `docker build .` does not work?

**Comment by lnielsen** [comment]
cc @crepererum

**Comment by lovasko** [comment]
I was thinking that this is maybe expecting some kind of volume mapping that is not mentioned (maybe is, sorry) or instead of the `COPY` we might use the `ADD` instruction.

**Comment by crepererum** [comment]
> This line https://github.com/inveniosoftware/invenio/blob/master/Dockerfile#L83 seems to be expecting a git clone of the invenio repository in the / directory inside the container.

Nope, it copies the listed files into the `/code` directory of the container (the path gets created because it does not exist at this point). It does not checkout the project in any root folder.

> Is there some special way to build the Dockerfile apart from `docker build .`?

Should their be one?

> If so, is it intentional that the basic `docker build .` does not work?

Can explain why it is not working?

For `COPY` vs `ADD` see
 - https://docs.docker.com/articles/dockerfile_best-practices/#add-or-copy
 - http://www.centurylinklabs.com/dockerfile-add-vs-copy/

The reason why we are not cloning the repo directly into the container is that you might want to make some changes to the code before letting Docker copying over everything. Making the modifications after the pull would be a lot of pain and does not provide any advantages. If you want to make live changes to the code (e.g. for development reasons), take a look at the [Docker Compose config](https://github.com/inveniosoftware/invenio/blob/master/docker-compose-dev.yml) which maps the source directory directly into the container.
