### ISSUE TITLE
oauth2server: oauth2CLIENT not cleaned if user is deleted

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3145]
I found that there is not any cascade action after a user is deleted.
So, e.g. if you run testsuite on tags module, at the end we have 14 rows in `oauth2CLIENT` table.

**Comment by lnielsen** [comment]
Actually I'm not sure if oauth2client table should be cleaned if a user is deleted.
Currently as it is now you can have data in the extra data variable, which you might not want to loose. I see two solutions, one is that the data is moved somewhere else, or alternatively we add support for marking a user as deleted without removing him/her from the database, so that we can still keep a record of what that user did.

**Comment by hachreak** [comment]
Ok, we need to discuss with @jirikuncar the best solution.
So, I think the behavior that you describe need a separate Issue.

To close this issue I propose to:
- [ ] Fix compatibility with PostgreSQL, making sure that SQLAlchemy will set NULL on user_id in oauth2CLIENT and oauth2TOKEN tables.
- [ ] Fix the testsuite to clean the tables after executing the tests.
