### ISSUE TITLE
SQLAlchemy: boolean value on PostgreSQL

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3215]
A Boolean column on PostgreSQL doesn't accept as True/False value as 1/0.

**Comment by jirikuncar** [comment]
@hachreak can you try to modify our `Boolean` column using http://docs.sqlalchemy.org/en/latest/core/custom_types.html#augmenting-existing-types?

**Comment by hachreak** [comment]
I already resolved the issue with: https://github.com/hachreak/invenio/commit/9888fb24e85734397124d1e3dc40722e8c2ef6c1

**Comment by jirikuncar** [comment]
:+1:

**Comment by tyan4g** [comment]
Is this problem fixed??
active = db.Column(db.Boolean, default=False)
then I'm trytin to save to db .
postgresql 
Error: Cannot save <class 'project.auth.models.User'> object, because (psycopg2.ProgrammingError) Error:   "active" type is  smallint,  boolean is given
LINE 1: ...d) VALUES ('15390df496865', NULL, 'qdLAI6pH', NULL, false, NUL...
