### ISSUE TITLE
RFC plotextractor Vs Flask-IIIF

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3222]
I'm reading the code inside plotextractor cli and I found function like [rotate_image](https://github.com/inveniosoftware/invenio/blob/master/invenio/utils/plotextractor/cli.py#L421).
It's still necessary or we can deprecate it in favor of Flask-IIIF?

@drjova @jirikuncar

**Comment by jalavik** [comment]
I think plotextractor probably can be deprecated from Invenio as it is only used by INSPIRE since it is directly tied with arXiv.org and the processing of tarballs from arXiv. It could either live on the INSPIRE overlay or separate package. Personally I favor the former.

Furthermore, this utility is "stable" and will probably not be touched much in the near future.

@kaplun @jirikuncar

**Comment by kaplun** [comment]
Yes, see also: #2853. We should add there plotextractor.
