### ISSUE TITLE
profile: nickname in profile form should not be mandatory ?

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3272]
Currently in the user profile form https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/accounts/forms.py#L183 the nickname is required.

This is somehow inconsistent with the way oauth authentication is working. If a site (like us on INSPIRE Labs) wants to rely fully on external authentication then all users have empty username.

If we enable the settings page and want to hide the user name (as it is not needed on our site) then the form cannot be validated when the user wants to change Given Names, email and so on.

Shall we change the profile form to not have nickname as mandatory?

**Comment by lnielsen** [comment]
We currently have two attributes for identifying a user (if they decide to login via the normal login form):
- ``email``
- ``nickname``

I assume the underlying assumption is that ``email`` is a better attribute because it's very practical for many other purposes than a nickname (e.g. password recovery just to mention one). 

It however also means that ``nickname`` falls in the category that I would call profile information, together with ``family_name`` and ``given_names``.

**Comment by lnielsen** [comment]
> Shall we change the profile form to not have nickname as mandatory?

I believe it still has to be mandatory, until we remove nickname as way to identify a user otherwise it may break other sites that users suddenly can remove their nickname. I might be wrong though, but at least I think it has to be thought through carefully.

I'm all in for simplifying this in the future. We currently have two attributes for identifying a user (if they decide to login via the normal login form):
- ``email``
- ``nickname``

I assume the underlying assumption is that ``email`` is a better attribute to identify users on because it's very practical for many other purposes than a ``nickname`` (e.g. password recovery just to mention one). 

It however also means that nickname falls in the category that I would call profile information, together with family_name and given_names, and ideally each site should allow to change what their profile information is.

**Comment by jirikuncar** [comment]
> ... all users have empty username

In case of external authentication methods, I would go for `nickname=email` (see https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/oauthclient/contrib/cern.py#L199).

**Comment by jmartinm** [comment]
> In case of external authentication methods, I would go for nickname=email (see https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/oauthclient/contrib/cern.py#L199).

That seems like like a good idea. I am going to give it a try adding it here https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/oauthclient/contrib/orcid.py#L124

If that works fine, is it ok for you @lnielsen that in orcid contrib we give as default ```nickname=email``` ?

**Comment by jmartinm** [comment]
I just realised that does not work for ORCID as in ```account_info``` we don't have the email address yet (ORCID does not provide it).

Possible solutions:

1) Set ORCID id as nickname in ```account_info```

2) Change in https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/oauthclient/utils.py#L94 ```nickname=account_info.get('nickname', '')``` by ```nickname=account_info.get('nickname', email)```

Option 2) might be better if we want to avoid in general having empty nicknames. What do you think?

**Comment by lnielsen** [comment]
> If that works fine, is it ok for you @lnielsen that in orcid contrib we give as default nickname=email ?

Hm, I'm not sure that will work either as you'll likely be exposing email addresses then (e.g. in messages, showing where a record comes from etc).

**Comment by lnielsen** [comment]
What about:

> 1) Set ORCID id as nickname in account_info

and perhaps modify add custom validator on nickname that checks a CFG variable to see if nickname is required....

**Comment by jmartinm** [comment]
https://github.com/jmartinm/invenio/commit/3ad8795485e10ce690221233905bd13e90f34722

Please, have a look at that commit. If it looks good I will do some more testing and create a PR against master.

**Comment by hachreak** [comment]
I'm working on [removing webuser](https://github.com/inveniosoftware/invenio/pull/3267) module and I found the following situation:

In webuser, exists a function [nickname_valid_p(nickname)](https://github.com/hachreak/invenio/blob/master/invenio/legacy/webuser.py#L378) to check nickname.
The function **doesn't** consider valid:
 - empty nickname
 - with space before and/or after
 - if it contains `@`

But, in [user registration](https://github.com/inveniosoftware/invenio/blob/c7c9b3e68c7d577e687763ac6b4a1e9ba564d5d3/invenio/legacy/webuser.py#L427) the check is bypassed for empty nickname (that, in the end, it's considered a valid nickname).

But, actually, in the `User` model there are no call to these check functions.

Yesterday, I asked to @tiborsimko and @jirikuncar about what we can consider "valid" nickname and they showed me 2 different, but equal "valid", visions about the problem.
So, I'm really interested in this conversation, because I'm moving and refactoring the validation of the nickname [from webuser to User](https://github.com/inveniosoftware/invenio/pull/3267/files#diff-10f346f902fdab6c4364e5e065da52c2R101).

**Comment by tiborsimko** [comment]
Some comments:

- Nickname was made mandatory so that we could display *some* user name without having to reveal his/her email identity.

- Nickname couldn't contain `@` because the login form was accepting either email address or nickname of users (that was functioning as a user name or sorts).  If nickname were allowed to contain `@`, you could imagine situations where `john.doe@cern.ch` email account could create nickname `jane.bar@cern.ch`, leading to confusions.  (We'd have to check uniqueness of both.)

IOW, if we want to allow `@` in nicknames, as e.g. in OAuth, we should make sure that all the login forms in the overlay accept only one attribute, or else that the attribute is forced unique by SSO mechanism, and not user settable.

**Comment by jmartinm** [comment]
Any comments on https://github.com/jmartinm/invenio/commit/3ad8795485e10ce690221233905bd13e90f34722 , shall I create a PR to master with it?

**Comment by hachreak** [comment]
@jmartinm have you see my PR? :)
What do you think if we move the check of nickname from access to User model?
Or, at least, in `invenio.modules.account.helpers`.
To avoid to have the validation checks spread in many place.

**Comment by jirikuncar** [comment]
@hachreak we need both checks - Form and Model, but they should be more or less in sync.

**Comment by hachreak** [comment]
I'm talking [about this](https://github.com/jmartinm/invenio/blob/3ad8795485e10ce690221233905bd13e90f34722/invenio/modules/accounts/forms.py#L45)
We can create a validation function inside the model User and the validation function for the form simply will be a call to this function with exceptions's catching.

**Comment by kaplun** [comment]
My god! :boom: @jmartinm @hachreak what is the situation of this ticket? Does it still make sense? Shall we attach a milestone?

**Comment by jmartinm** [comment]
On my side its ok.

The original problem was worked around by https://github.com/inveniosoftware/invenio/pull/3378
