### ISSUE TITLE
global: CFG_SITE_NAME and root collection dependency ?

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3273]
Related to https://github.com/inspirehep/inspire-next/issues/248

on INSPIRE we are wondering if `CFG_SITE_NAME` has still to be named in the same way as the default collection. In the past that was the case e.g. so that empty search queries would find the records in the Default collection.

That is a problem as some code uses `CFG_SITE_NAME` when sending emails to users so we are limited by the way we can name the site and the default collection.

**Comment by jirikuncar** [comment]
Can we consider that *root* collection has `id` equal 1 or we have special configuration option `COLLECTION_ROOT(S)`?

**Comment by kaplun** [comment]
> Can we consider that root collection has id equal 1 or we have special configuration option COLLECTION_ROOT(S)?

Indeed so far the convention was that root collection is simply the collection from which a search would start if no collection is defined. Otherwise Invenio always supported forests of collections.

Somehow what is needed is to be able to define a default collection. Root collections could be simply defined as collections not having any parent.

**Comment by jmartinm** [comment]
For the INSPIRE use case that started this, it was solved with https://github.com/inveniosoftware/invenio/commit/f4bf802ef8e11c2a677db0afa2ffba93001da353

I leave it open in case you want to keep discussing how the default collection should be defined.

**Comment by jirikuncar** [comment]
@jmartinm I will close this issue and new discussion can start when we separate module to `invenio-collections`.
