### ISSUE TITLE
pages: admin not showing content column

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3311]
I guess after the introduction of this commit:

https://github.com/inveniosoftware/invenio/commit/47e2031f6d9b95eb13d5fc0bbe0df3cf7b1db09d

The Flask-Admin for the pages module does not show the Content anymore (which is quite important ;) )

![screenshot 2015-06-25 14 59 36](https://cloud.githubusercontent.com/assets/580727/8354809/48828058-1b4b-11e5-9735-773e77274873.png)

Any idea why this might be? @hachreak

**Comment by hachreak** [comment]
It seems that the problem is when you use [with_variant()](http://docs.sqlalchemy.org/en/rel_1_0/core/type_api.html?highlight=with_variant#sqlalchemy.types.TypeEngine.with_variant).

```python
db.Text().with_variant(db.Text(length=2**32-2), 'mysql')
```

I asked directly to Mike for this solution.
Maybe Flask-Admin can't undestand it because it returns a `Variant` Object?

See: https://bitbucket.org/zzzeek/sqlalchemy/issue/3370/text-and-length#comment-17513621

**Comment by jmartinm** [comment]
Maybe you can create an issue in https://github.com/flask-admin/flask-admin @hachreak ?

**Comment by jmartinm** [comment]
The issue is still open https://github.com/flask-admin/flask-admin/issues/912 for the moment.

**Comment by bouzlibop** [comment]
This should help: `form_overrides = dict(content=TextAreaField)`
https://github.com/zenodo/invenio/pull/7/files#diff-b83bf3bae0fb93452518c475004ffe97R89

**Comment by jirikuncar** [comment]
@bouzlibop can you please submit a patch for *Invenio-Pages*?
