### ISSUE TITLE
RFC nickname check rules

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3341]
I'm trying to:
- rewrite the access module #3328 
- remove WebSession legacy module #3326 
- remove WebUser legacy module 3267
- rewriting "lost password" forms and email #3326

I wrote a special function on the models to check nickname.
But, actually not all agree on which rules I should follow.

I write here the list of rules that we should be sure is applied (and check the rules accepted by all):
- [x] nickname not empty
- [ ] unique nickname
- [x] can't contain "specials" char as `@` and `,`
- [x] can't start with empty spaces
- [x] can't end with empty spaces
- [x] it can't be `guest`
- [ ] accept a subset/not ambiguous on unicode chars

Are all agree? :)

**Comment by jmartinm** [comment]
Thanks Leo. The rules for the nicknames seem good to me in principle. I guess the `it can't be guest` is due to legacy code relying on that name? In an ideal world that should not be a limitation?

And is the nickname mandatory in the end? Or having an email is enough? Most sites treat both as the same:

```python
nickname/email: [    ]
password: [    ]
```

is it possible to do that?

**Comment by crepererum** [comment]
## Clarification for the Unicode point

Google faced the same issue with Gmail (see [blockpost](http://googleonlinesecurity.blogspot.ch/2014/08/protecting-gmail-in-global-world.html)) and decided to use a very good official specification called [Unicode Restriction Level](http://www.unicode.org/reports/tr39/#Restriction_Level_Detection). We should choose one of the levels described there. I propose [3 - Highly Restrictve](http://www.unicode.org/reports/tr39/#highly_restrictive).

For Python there exist a library that can be used to test this: [idncheck](https://github.com/soulshake/idncheck) (originally intended to check domain names, but the functionality is exactly what we need here)

## Blacklisted words
Should we blacklist some words (make it an admin option), e.g.
 - **system-like roles**: `guest`, `reviewer`, ...
 - **bad words** (maybe from a some anti-spam list)

## Length
Should we require a minimum length, e.g. 4 characters?

**Comment by hachreak** [comment]
@jmartinm currently, in the code exists 3 point where validate/update nickname and them require that nickname can't be empy:

https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/accounts/validators.py#L79
https://github.com/inveniosoftware/invenio/blob/master/invenio/legacy/webuser.py#L386
https://github.com/inveniosoftware/invenio/blob/master/invenio/legacy/webuser.py#L504

And another one where I'm not sure if it permits empty nickname (maybe yes):

https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/access/admin_lib.py#L1051

**Comment by jirikuncar** [comment]
:+1: for https://github.com/inveniosoftware/invenio/issues/3341#issuecomment-119891054

**Comment by tiborsimko** [comment]
`nickname` used to be optional in the beginning, but it has been mandatory since many years now.  It basically plays a role of "visible username" or a "visible user ID" or "visible user handle".  In this way the user email address stays hidden.  When people register, they need to select one.  When we use external authentication, we fetch the user ID from the remote system.  (E.g. for CERN SSO it can be either login name, or first part of the email address up to `@`, etc.)

:+1: for restricting dangerous Unicode and other "reviewer" and the like nicknames via `idncheck`.  (Though beware that our "root" user has "admin" nickname by default.) 

After we severe the nickname rules, the upgrade recipe can warn the site admins if some of their users have improper nicknames.

**Comment by aw-bib** [comment]
Is it still viable to live in 7bit ASCII for the login? Ie. apply unix rules for the nickname? Just had quite some fun in projects that did not follow this seemingly simple rule (e.g. also considering to hook up more restrictive systems.)

**Comment by hachreak** [comment]
@tiborsimko @jirikuncar  on "nickname can't be empty":

https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/oauthclient/contrib/orcid.py#L124

If you login with Orcid, invenio doesn't collect information about nickname!
Can we set a nickname?

**Comment by lnielsen** [comment]
Orcid is already setting the family name: https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/oauthclient/contrib/orcid.py#L175

**Comment by hachreak** [comment]
But at that point it's late because the user is already created.
I tried to add a SQLAlchemy "validator" to check nickname but orcid tests failed.

**Comment by jmartinm** [comment]
@hachreak I should backport this commit from our INSPIRE repo https://github.com/inspirehep/invenio/commit/44e23568a6dce15c1f6b2a258c5ecbdf318a0543

**Comment by jmartinm** [comment]
Here the PR https://github.com/inveniosoftware/invenio/pull/3378

**Comment by hachreak** [comment]
@jmartinm cool! thanks! :D

**Comment by jirikuncar** [comment]
Solved in https://github.com/inveniosoftware/invenio-userprofiles/blob/master/invenio_userprofiles/validators.py#L41-L48
