### ISSUE TITLE
WebAccess: delete user accounts

### ISSUE THREAD

**Issue by BessemAamira** [inveniosoftware/invenio#3521]
Deleting user account via WebAccess, does not remove groups who has been created by these users ( user_usergroup and usergroup table)

**Comment by tiborsimko** [comment]
@BessemAamira Which Invenio version is this for?

**Comment by BessemAamira** [comment]
@tiborsimko  version 1.1.6

**Comment by tiborsimko** [comment]
This would require a feature flag, becase removing groups may or may not be a good idea:

- Use case 1: a real user created a topical group and would like to "hand it over" to somebody else. (We should not delete groups in this case, only change "owner".) 

- Use case 2: a user created many test accounts and test groups, and the administrator would like to remove them all easily.

Since Invenio 1.1 is an "old" stable release that is feature frozen, we'd have to implement this in later Invenio versions, such as forthcoming Invenio 1.3 legacy release. Please open a new issue if you still need this?

(Otherwise, as an admin, please note that you can use `dbexec` and alter SQL tables manually.)
