### ISSUE TITLE
WebSession : user group list 

### ISSUE THREAD

**Issue by BessemAamira** [inveniosoftware/invenio#3526]
The List of user groups in user_info include groups which user has requested to join (pending 
status ).
this may cause dysfunction in the authorization roles especially "firewall like role definition" using group.

I propose to modify the sql request in get_groups function(webgroup_dblayer)
 query = """SELECT g.id, g.name
               FROM usergroup g, user_usergroup ug
               WHERE ug.id_user=%s AND
                     ug.id_usergroup=g.id AND
             ug.user_status<>'P'
 Invenio 1.1.6 release

**Comment by tiborsimko** [comment]
@BessemAamira The SQL query seems correct. The `<> 'P'` part makes sure that pending members aren't included.  (P=pending, see `CFG_WEBSESSION_USERGROUP_STATUS`). If you saw some pending users being included in a group where they should not have been included yet, then the problem is probably elsewhere.  @kaplun Have you seen something similar in relation to fireroles?

**Comment by kaplun** [comment]
@tiborsimko I am bit confused. I believe the PR #3652 by @jirikuncar is already fixing what @BessemAamira reported. the groups in `user_info` are computed at login time via `get_groups` that is corrected in the mentioned patch. So I think this ticket can be closed.
