### ISSUE TITLE
Error in building docker

### ISSUE THREAD

**Issue by shemgp** [inveniosoftware/invenio#3544]
I tried to follow the instructions here: http://invenio.readthedocs.org/en/latest/installation/installation-quick.html

And it had an error when I was running: 
docker build -t invenio:2.0 .
Here's the error:
 ---> Running in 6557760540bd
Command "/usr/local/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-ociO2Y/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MncOSU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ociO2Y/Pillow
The command '/bin/sh -c python requirements.py --extras=$REXTRAS --level=min > requirements.py.lowest.txt &&     python requirements.py --extras=$REXTRAS --level=pypi > requirements.py.release.txt &&     python requirements.py --extras=$REXTRAS --level=dev > requirements.py.devel.txt &&     pip install -r requirements.py.$REQUIREMENTS.txt --allow-all-external --quiet' returned a non-zero code: 1

Thanks for your help.

**Comment by tiborsimko** [comment]
> error code 1 in /tmp/pip-build-ociO2Y/Pillow

Are you well on the latest `maint-2.0` branch?  I.e. do you have the following patch?

- 50373f9a78f53456a90a528628340d8bd5c6f966

(With this patch, I verified about a week ago that the build process succeeds.)

BTW this kind of problems may also appear due to network connection troubles, such as connected to docker process loosing connection due to laptop's suspend/resume, for example.  You may debug the problem by editing your `Dockerfile` and removing the `--quiet` mode. This will print the detailed information on what went wrong.

**Comment by shemgp** [comment]
Yes, that patch wasn't applied to my copy of maint-2.0.  Had to do git pull to make it work.  It's working now. Thanks.
