### ISSUE TITLE
Vagrant installation broken

### ISSUE THREAD

**Issue by timrobertson100** [inveniosoftware/invenio#3688]
Hi folks

When running the [vagrant installation](http://pythonhosted.org/invenio/installation/installation-quick.html#using-vagrant) you get a `502 Bad Gateway` error on trying to access http://192.168.50.10/records/1

From the web VM you get errors in the nginx log:
```
vagrant@web:~$ sudo tail -f /var/log/nginx/error.log
2016/08/23 15:02:49 [error] 12834#0: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.1, server: localhost, request: "GET /records/1 HTTP/1.1", upstream: "http://127.0.1.1:5000/records/1", host: "192.168.50.10"
```

**Comment by tiborsimko** [comment]
I have just tested the Docker installation and the Vagrant installation from scratch, and everything works well for me.  I'm therefore closing this issue.  Can you please retry? If you encounter any problems, please just reopen it.

FWIW I tested on Ubuntu 16.04 LTS with Vagrant 1.8.1 and Virtualbox 5.0.24.

P.S. Perhaps your issues have been transient due to some temporarily non-working invenio package dependency that was released in "alpha" state on PyPI.  Installing `master` branch is often on the bleeding edge of things...

**Comment by timrobertson100** [comment]
Thank you very much @tiborsimko 

Confirmed that it does indeed now run, and I suspect it was a transient issue with PyPI as I did not do a pull today, but simply reran the process.
