### ISSUE TITLE
RFC commit message style and release notes

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3723]
### About

This RFC summarises reasons behind [git commit log message style](http://invenio.readthedocs.io/en/latest/technology/git.html#r2-remarks-on-commit-log-messages) that
was born in the Invenio 1 (and 2) monolithic world. Most of the original reasons
do not apply in the Invenio 3 independent package world anymore. Now that we are
approaching the first Invenio 3 stable release, the time is perfect to reflect
on the existing practices and how to improve them.

**Note:** This will be the topic of an [Invenio Developer Forum](https://indico.cern.ch/category/6046/) 
live discussions, so even though every one is encouraged to comment in here, it would
be great to meet up and reflect on the matter IRL together.

### 1. General upstream conventions

Upstream git conventions talk about a commit log headline, followed by a blank
line, followed by the multi-line body. Just as we use PEP-8 for Python code, we
use these upstream general git conventions for commit log messages. (Users of
Emacs, Vim and possibly other code editors have a "commit log mode" that helps
to format the messages according to these general conventions.) This RFC is not
questioning these; it focuses solely on the Invenio-specific semantics expressed
inside.

### 2. Commit headline format

In Invenio 1 (and 2), the convention was to use:

    component: brief description

permitting to rapidly distinguish commits to various modules:

    BibFormat: initial release of mobile app formats
    WebSearch: display number of hits in mobile output
    BibDocFile: improve BibDoc display in Files tab

In Invenio 3, the modules have been split into independent packages, making the
original intent not applicable.

Do we consider the separate leading component as still useful? If so, do we use
it to denote component of a package (docs, test, ui, core, api, etc) or nature
of the commit (bug, feature, enhancement, etc) or something else? If not, do we
prefer the headline to be a simple free style phrase? Do we pay attention to
headlines while bisecting?

### 3. Commit signatures

In Invenio 1 (and 2), we have been using Trac and Jenkins, the commit signatures
expressed the commit kwalitee and review status:

    Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
    Reviewed-by: Tibor Simko <tibor.simko@cern.ch>
    Reported-by: Tibor Simko <tibor.simko@cern.ch>
    Co-authored-by: Tibor Simko <tibor.simko@cern.ch>

In Invenio 3, we are using GitHub where centralised reviews happen, and Travis
where commit quality and CI tests are enforced.

Do we keep some of the signatures to express credit for reporting and/or
co-authoring? Do we remove all signatures?

### 4. Release notes vs commit notes

In Invenio 1 (and 2), the point releases were rare, and services such as INSPIRE
often used ``master`` branch in production, and wanted to know what changed
precisely between any two given ``SHA1a`` and ``SHA1b``. Hence the release notes
that were compiled "live" for any commit log message range:

    kwalitee prepare release -c sha1a..sha1b

In Invenio 3, the point releases of various packages happen very frequently and
services are often deploying from PyPI releases only. (Side note: pinning
specific versions that are "waiting" for release due to some blockers.)

Do we consider it useful to keep relying on git log based messages to compile
release notes? Do we consider it sufficient to maintain a separate RELEASE-NOTES
file dissociated from commit logs? Do we consider it useful to be able to
compile changes automatically at any point in time? Do we compile them only at
the release time? Do we pay attention to release notes vs commit notes while
bisecting?

### 5. Release note classification

In Invenio 1, the release note messages were originally compiled from short
commit log headlines, see for example [1.1.0 release notes](https://github.com/inveniosoftware/invenio/releases/tag/v1.1.0).
This was often too brief to be understandable by the users.

This led to the introduction of commit log labels such as NEW, BETTER, FIX in
front of longer sentences, so that the release notes would be much more
self-understood and and categorised. See for example [1.2.1 release notes](https://github.com/inveniosoftware/invenio/releases/tag/v1.2.1).

Do we want to keep or amend the NEW/FIX/BETTER/SECURITY/etc release note
classification?

### 6. Release note author

In Invenio 1 (and 2), the release notes were created from the commit log
messages via commands like:

     kwalitee prepare release -c v1.1.6..

Hence it was important to use proper English phrases in the commit log messages.
Oftentimes developers didn't pay attention to this, which necessitated (i)
cherry-picking by the maintainer and/or (ii) rebasing by the developer.

Do we want the release note messages to be written by the contributors or by the
maintainers? Do we let maintainers rewrite the release notes either by
cherry-picking, or by using explicit merge commits, or by maintaining a separate
file, or by amending GitHub issue body, etc? Is the PR author the best person to
think of the release message? Is it the maintainer?

### 7. Body format

In Invenio 1 (and 2), the convention was to use itemised list:

    * BETTER Improves foo.

    * FIX Fixes bar.

permitting to express different facets of what the given commit does. (For
example, enhances a feature and fixes a related bug at the same time.)

Do we consider this still useful? Do we require one commit to announce one thing
and one thing only?

### 8. Issue integrations

In Invenio 1 (and 2), the link between commits, PRs, and issues were expressed
via usual directives:

     (addresses #1234)
     (closes #1234)

The format was parenthesised so that release notes could be properly compiled.
Some developers didn't use this format, requiring usual amendment cycle. Are we
happy with the practices? Are we remove the constraints?

### 9. Message format checks

If we retain using some structured commit message format, it should be easy to 
check and plug into Travis CI. Currently, we use:

    kwalitee check message master..upstream/pr/13

and this is plugged into CI for several repositories. Do developers run these locally? 
Do we plug these into Travis CI everywhere?

### Proposal time!

The above points summarised the main reasons behind current practices. Many of
the reasons are no longer valid in the world of Invenio 3 distributed packages.
Now that we are about to release the first Invenio 3 "production" packages,
the time is good to ponder and improve the system.

The high-level goals for selecting a consistent commit note system for Invenio
packages:

- the commits should be atomic etc (as usual);
- the commit message should describe changes fully, so that it would be
  self-understood what the commit does, even without reading the code;
- the commit notes should facilitate later bisecting;
- the release notes should be easily maintainable and not prone to getting 
  forgotten or getting out of sync with the code;
- the release notes should be informative to the users.

Let's discuss any finer points and any proposals live at an [Invenio Developer Forum](https://indico.cern.ch/category/6046/).

CC @inveniosoftware/developers

**Comment by aw-bib** [comment]
> the release notes should be informative to the users.

This requires IMHO to define the target user first. Early adopters of new code staying on the bleeding edge all the time would probably go for the commit messages and skip release notes. User who just run a service with occasional upgrades may feel that release notes are much more important. E.g. as we are running way behind the bleeding edge I tend to checkout release notes closely but do not dive through the last months of commits.

**Comment by Kjili** [comment]
If the problem is that developers don't run kwalitee locally or just to ease the correct formatting of a commit, there's this tool: https://github.com/commitizen.
The preferred styling can be chosen through given adapters or by building one's own adapter, so it would be possible to combine it with kwalitee if desired.
It does not enforce usage and it's not needed either, but it makes commiting in the correct style a lot easier. Also, it tries to address the matter from the angle of _avoiding_ styling mistakes in contrast to _checking_ correctness after committing which requires additional action if errors were found that need correction.

**Comment by aw-bib** [comment]
Still, following the discussion on Vidyo I had the impression that there were  basically two kind of people present. The first two of the following list.

- Developers as you call them. Those guys you envision here follow the bleeding edge anyway, run on the latest code, don't need any release notes and thus don't want to care about them. Usually, however, they _do not_ run a productive system.
- There is (to my experience) a second sort of developers that are a bit more relaxed concerning the blood, and don't follow the latest line of every commit or only parts of the project. They'd probably like distilled versions from modules they don't really care too much about (assume them working and less relevant) while they follow more closely the stuff relevant to them. They are more likely to _run_ a productive system  or are the second or third level support.
- Mere mortals (like me) are happy if they can weed through  a _distilled_ version of important changes _after the year or so_ when `git pull` happens. People like me don't like this release with every commit idea at all. I fear, I have to run systems in production. Keeping those running is the foremost concern. New features are not. In my world a release cycle of 2 years is _quite fast_ but probably do able. Everything faster is _unusable_. So, it might well be that I have to read _several_ release notes in sequence, mentally diff them to get the relevant part. This makes them a bit more important to me than the individual commit message as such.
- _Users_ of invenio would IMHO also like a release note. Much more, they would prefer stable packages with sensible configs in a decent Linux (server) distribution and thus don't care too much about it as it's mainly the maintainers stuff. Still one likes to get again a distilled list of important changes. E.g. I usually read the release notes of my _core tools_ in detail to check if some changes affect me or if there is some useful new stuff. Ie. in an ideal world I for myself would fire up `vim` to read the release notes after `apt-get install invenio` on my Debian stable server and then edit only config files, but I'd not write any line of python at all to get it running. However, I fear these people are not and will never be targeted by invenio.  (One _can_ have dreams though ;)

I think before discussing  fullstops at line ends, the usage of lists vs. prose or past/present tense formulations of more or less English text  one should be sure to know the target audience of the resulting document. I admit I don't care at all if it's past or present, if it's a bullet point list or prose. I am with @jirikuncar that it should probably be on the level of email. (Czech, however, would be a different issue due to _my_ limitations ;)

Additionally, I frankly admit, that some of the few lines of code I was able to contribute to invenio in the current scheme sometimes took me a few minutes to write while I had some tough and longish fight to get the commit right (and still failed as some of you know all too well). OTH I only did it once in a while so it was always basically starting from scratch.

Still I'd argue that one should have at least the mere mortals of the above list in mind and probably invest some work for them even if it delays some fancy new something.

**Comment by kaplun** [comment]
> Mere mortals (like me) are happy if they can weed through a distilled version of important changes after the year or so when git pull happens. People like me don't like this release with every commit idea at all. I fear, I have to run systems in production. Keeping those running is the foremost concern. New features are not. In my world a release cycle of 2 years is quite fast but probably do able. Everything faster is unusable. So, it might well be that I have to read several release notes in sequence, mentally diff them to get the relevant part. This makes them a bit more important to me than the individual commit message as such.

@aw-bib, you should note that  *more frequent releases* is disjoint from *new features*. In Invenio packages carefully apply [semver](http://semver.org/) then in principle we can have one release per bugfix (thus increasing the minor version), and you can apply these on production without worry (as you do with any other deb/rpm package in your production system). You just need to limit dependencies to minor versions. E.g. you say `invenio-records==1.0.*`. You won't have scary new features, but you'll benefit bug/security fixes.

**Comment by david-caro** [comment]
Just to add another 'production system maintainer' opinion:

* I'm a mere mortal too, I'm happy if I get a distilled version of important changes, specially, the separation between features/fixes and backwards compatible/incompatible. That allows me to decide if a package/lib/whatever can be easily upgraded or not.
* But, this must be strongly paired with a semantic versioning schema. That is, make the version number useful, BUMP the major, when there's a non-backwards compatible change, so I can pin to the major version and still get the new features for that version and bugfixes.
* I really try to avoid pulling once a year (that will require a HUGE amount of effort every time you upgrade, and a lot of pain afterwards to fix everything that was broken), instead, my goal is to deploy at least once a week all the minor versions and once a month all the major upgrades (that we want in). That lowers considerably the total amount of work needed, smooths the upgrades, and allows faster and easier track/adaptation/fix of features and bugs. I think that at this point, we have enough examples in the real world that doing smaller more frequent upgrades is way smoother in every way than doing huge, yearly ones.

**Comment by fjorba** [comment]
Dear Alexander et al,

At Thu, 24 Nov 2016 01:10:12 -0800, Alexander Wagner wrote:
> 
> Still, following the discussion on Vidyo I had the impression that
> there were basically two kind of people present. The first two of
> the following list.

thank you for handling me a copy of your thoughts, as I cannot follow
those discussions.  Your words are my words.  I agree on all your
thoughts.  I am a mere mortal, and frankly, I feel myself alienaded
since quite a few months of Invenio development.  I cannot follow this
path anymore.

It appears as if you, the developers, are racing a race with your
colleagues about which new tool or toy is newer or cooler, without
having a second thought about whether it will help normal,
non-developers Invenio administrators.

As a trivial example about release notes, it took myself a few hours
to document locally the changes between our current upgrade from 1.1.2
to 1.1.6, as the developers notes don't make much sense to librarians
(currently 2 of our 3 production sites already upgraded).

Thanks for listening,

Ferran

**Comment by aw-bib** [comment]
> note that more frequent releases is disjoint from new features

This is understood as long as the frequent releases are on the patch level.

@kaplun I understood the semver issue you mention and this is something I like, provided your `if` clause stays true :) `apt-get upgrade` is fine with me as well. I'd prefer to have it in `apt` instead of something else, but this is out of the question here. Still, for us as a multi-host multi-site project roll-out has some implications. So for mere practical reasons (admin schedules and such things) IRL we may very well jump from patch level 1 to 245 in one go. Here it is of some practicality if I can easily check what's already included in 1..245, as 173 may require/enable us to disable a local patch.

@david-caro besides we agree, note that we currently live in legacy world. Ie. 1.1.x. Yes, we deploy the x. At the time of writing this _pull once a year_ is slightly over exaggerating the current release cycle on that branch. I used it more metaphorically, that we do not check each and every commit or follow closely the very latest developments as they are currently _far, far away_.

I admit that I do not yet see if this strong modularization of invenio 3.x will be of any benefit to us. I'm sure it will change a lot. What I'm pretty sure about is that roll out once a week is at least challenging. Right now we manage a monthly schedule. Invenio GA + our overlay that is. Usually we deploy changes in our overlay. For invenio GA it is usually longer than one month. 1.1.7 is in preparation, I think. It will allow us to drop some of our patches... Checking release notes ;) This requires some preparation.

**Comment by david-caro** [comment]
@aw-bib Sure, I was talking about invenio >=3 branches/projects, as it's not easy nor practical to do with the old legacy ones, I completely agree with that. It's also nicer as you really should not care about the release notes of any of the dependencies, and the module separation will allow you to ignore a bunch of them making the release notes of invenio way clearer and relevant.

In any case, the migration to invenio 3 should come sooner or later, so well, you should probably keep it in the back of your mind too ;)

**Comment by aw-bib** [comment]
> It's also nicer as you really should not care about the release notes of any of the dependencies

I admit, I tend to buy this only in _futur II_ (Once I will have seen ... ;) But it would be nice.

**Comment by jma** [comment]
Concerning the log format, `angularjs` use a specific convention that can be a source of inspiration:

[https://gist.github.com/stephenparish/9941e89d80e2bc58a153](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
