### ISSUE TITLE
Cannot login into invenio demo: The CSRF tokens do not match.

### ISSUE THREAD

**Issue by exedre** [inveniosoftware/invenio#3815]
I installed the invenio demo using docker-compose commands.

The web interface is ok and I access to records but if I try to login to user (info@inveniosoftware.org pass uspass123), the error is "The CSRF tokens do not match."

This remain true even if I change user and pass and rebuild all by scratch.

<img width="892" alt="screenshot 2017-07-15 23 54 03" src="https://user-images.githubusercontent.com/82950/28243051-ef3418cc-69bd-11e7-92cf-c97c4c9b049d.png">

```
OS is MacOS 10.11.6 
docker: Version 17.06.0-ce-mac19 (18663)
$ invenio --version
Flask 0.12.2
Python 2.7.13 (default, Jun 21 2017, 18:17:05) 
[GCC 4.9.2]
```

**Comment by hachreak** [comment]
Just for the moment you can try the workaround `ACCOUNTS_JWT_ENABLE = False` in your `invenio.cfg` file.
With @drjova, we will found a better solution.

**Comment by hbayindir** [comment]
I'm having the same issue with the Docker installation.

**Comment by lnielsen** [comment]
We're fixing this issue now during our current sprint. ETA ~1 week

**Comment by hbayindir** [comment]
@lnielsen Magnificent! Thanks!

**Comment by hachreak** [comment]
We found the problem!

Its because we enable Talisman `session_cookie_secure` by default.
It will [disable the session cookie](https://github.com/lepture/flask-wtf/issues/76) if you are not in https.

So, the solution is to enable `DEBUG=True` or manually disable `session_cookie_secure`.

----------------------------------------------------------------
cc @lnielsen @diegodelemos

**Comment by hbayindir** [comment]
@hachreak Maybe a small howto for adding required certificates for proper SSL installation can be added to installation documentation. No? 😄
