### ISSUE TITLE
how to upload publications?

### ISSUE THREAD

**Issue by nerkn** [inveniosoftware/invenio#3847]
I freshly installed invenio and I cant find any upload link or option. Now I have a script to upload zenado, which is also using "invenio". but there is upload link, listing etc.
How I may upload publications? which links does invenio support for crud operations.

**Comment by lnielsen** [comment]
You'll have to use something like https://invenio-deposit.readthedocs.io/en/latest/ but it's not finished yet

**Comment by nerkn** [comment]
Hi inielson, I saw that you have closed the issue but I think deposit module still not working? 
There is no way to use invenio as repository ?

**Comment by lnielsen** [comment]
Invenio-Deposit is being used in production systems on zenodo.org, videos.cern.ch and other internal systems, so the module is working. However, documentation of the module is close to non-existing and it's hard to use. 

The reason for closing your ticket is not because we don't care, but rather that the issue is already part of many other issues that we're already tracking. We're trying our best to get to more user-friendly version with proper documentation, but it's a lot of work and we don't have a lot of resources, so it's, unfortunately, going to take some time.

**Comment by ayssi** [comment]
Hi all,
any news about the deposit module ?
Thanks
