### ISSUE TITLE
No such file: styles.scss

### ISSUE THREAD

**Issue by devolt5** [inveniosoftware/invenio#3922]
Hi,

I followed the Instructions on: https://invenio.readthedocs.io/en/latest/quickstart/quickstart.html
All seemes fine, but when I open https://127.0.0.1:5000/ I get the following error:

`IOError: [Errno 2] No such file or directory: '/home/user/.virtualenvs/my-repository-venv/var/instance/static/scss/invenio_theme/styles.scss'`

Which is right, static contains only a package.json. The files needed are located in /lib/python2.7/site-packages/invenio_theme/static.

What went wrong? Is there another npm install needed? Is there something missing in docker-compose?

Greetings!

**Comment by diegodelemos** [comment]
Hello @devolt5! First of all thanks for trying out Invenio :)

I went through the instructions and I couldn't reproduce the issue, so lets find out what's wrong with some questions
- Did you strictly follow the docs? The cookiecutter instructions are pinned to v3.0 wich is stable.
- Do you have Invenio installed inside your system Python? When this happens you might run into the issue that the global Invenio installation is being called, instead of the one inside the virutalenv (could happen [here](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/v3.0/%7B%7Bcookiecutter.project_shortname%7D%7D/scripts/bootstrap#L12)).
```console
$ which invenio
/usr/local/bin/invenio
# instead of
$ which invenio
/Users/username/.virtualenvs/the-invenio/bin/invenio
```

**Comment by ProgrammfabrikGuest** [comment]
Thanks for the hint!

`$ which invenio` showed nothing. Then I checked my npm version, which was below the minimum requirements. For safety's sake, I changed the Python version to 3.
`$ ./scripts/bootstrap` then compiled a bunch of js and css files, which was a good sign. 

Which Python3 version is suggested by you at the moment?

Now, everything's fine!

**Comment by devolt5** [comment]
Thanks for the hint!

`$ which invenio showed nothing.` Then I checked my npm version, which was below the minimum requirements. For safety's sake, I changed the Python version to 3.
`$ ./scripts/bootstrap` then compiled a bunch of js and css files, which was a good sign.

Which Python3 version is suggested by you at the moment?

Now, everything's fine!

**Comment by devolt5** [comment]
Didn't see that. Sure.

**Comment by diegodelemos** [comment]
Documented in https://github.com/inveniosoftware/troubleshooting/issues/45.
