### ISSUE TITLE
docs: enhancement and visibility improvement of the development environment docs

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/invenio#4035]
The current [development environment docs](https://invenio.readthedocs.io/en/latest/community/development-environment.html) are quite hidden and need to be updated (source [here](https://github.com/inveniosoftware/invenio/blob/master/docs/community/development-environment.rst)). these docs are not very used:
- We should improve its visibility (through https://github.com/inveniosoftware/inveniosoftware.org/issues/133 ?)
- Improve its usability, make it easier for developers

**Comment by FlorianCassayre** [comment]
## Documentation structure proposal

([current documentation for reference](https://invenio.readthedocs.io/en/latest/))

- Getting Started
    - Overview *(renamed from Introduction)*
        - History
    - Quickstart
    - Getting help
    - Communication channels *(find a better name?)*
    - Developer env *(find a better name? maybe "Local development")*

- Tutorials
    - Invenio training

- Documentation
    - Requirements
    - Main concepts
        - Repository structure *(renamed from Build a repository)*
        - Understanding data models
        - Managing access to records
        - Integrating Files
        - ***Securing your instance***
        - Application architecture
        - Infrastructure architecture
    - Invenio Bundles
        - Overview
        - 
    - How to
        - Login with ORCID 
        - ***Secure your instance***
        - Build a module
    - Releases
    - Upgrading
        - Migrating to v3
        - Marshmallow v2/v3 compatibility

- Community
    - Contributing
        - How to contribute
        - Style guide
        - Translation guide
        - Maintainer's guide
    - Code of conduct
    - Security Policy
    - Governance
    - License

### Ideas

- Shall we have Tutorial and How-to in the same section/box?
- Where does "Securing your instance" belong to?

### Pages to be deleted

- Developing with Invenio (already in the training)

## Mockup

The new menu is inspired from other successful solutions ([Docker](https://docs.docker.com/), [Wordpress documentation](https://wordpress.org/support/), [Drupal](https://www.drupal.org/documentation), [Kubernetes](https://kubernetes.io/docs/home/), [React](https://reactjs.org/docs/getting-started.html)). The idea is to preserve consistency between the organization website and the documentation on readthedocs, while improving the user experience (easier access to what they are looking for).

![image](https://user-images.githubusercontent.com/9027075/90407974-7678a600-e0a7-11ea-852a-2a91ea838df7.png)

The order of the three blocks also needs to be discussed.

**Comment by lnielsen** [comment]
Great work!!! Thanks a lot. Here's my feedback/thoughts/comments:

1) I like the documentation frontpage from e.g Docker and Kubernetes. See also [CockroachLabs](https://www.cockroachlabs.com/docs/stable/). That said, I always have a hard time navigating the Docker documentation beyond the frontpage.

2)I would like that each product is made a bit more equal similar to e.g. the frontpage. You could have three columns.

3) We discussed having a search field, that allows you to search e.g. github inveniosoftware organisation. That I woudl put in the top.

4) We should take not to duplicate the structure because then someone has to remember to maintain it (otherwise it gets outdated). From experience, this will happen unless there's automatic sync.

5) Have you identified the different audiences and what they would possibly be looking for? I can think of e.g. these:
- New Invenio developer (at CERN or outside CERN) -> developer environment setup, quickstart  with RDM/Framework/ILS. Training, High-level overview, Support forum, where to ask questions
- Experienced invenio developer -> Module level API documentation, Search, Release notes/Upgrade guides
- First time user (e.g. sysadmin): Quickstart with RDM/ILS, list of features, Support forum, where to ask questions
- Experience user (sysadmin): How to customize, user focused Plugins/extensions documentation, how tos, Support forum, where to ask questions

6) I would link from for the overview page to each individual module documentation (somewhere in the bottom).

Let's discuss further in person.
