### ISSUE TITLE
RFC Generic BibTeX export

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#662]
Originally on 2011-06-06

Currently **BibTeX** export is generated out of the box, by using a single *output format*, calling a single *format element*, namely `bfe_bibtex.py`. This imply the business-logic of the BibTeX export is all hard-coded in one place and can not easily be adapted to the most different document type. This has an impact, e.g. in CDS, when exporting Thesis documents.

One possible solution would be to have generic `bfe_bibtex_field.py`, based on `bfe_bibtex.format_bibtex_field`, able to format certain subfields, and to provide demo BibTeX exports, that are adapted to the specific document type.

**Comment by jirikuncar** [comment]
@bouzlibop is it related to the work you have done for Zenodo BibTex formats?

**Comment by bouzlibop** [comment]
I've done some work in regards to BibTeX, which is now working in Zenodo. See [this](https://github.com/zenodo/zenodo/blob/master/zenodo/base/utils/bibtex.py).

Nonetheless I'm not sure if it is sufficient when it comes about things discussed here. Some limitations of this above mentioned BibTeX formatter are eg. not being able to distinguish between phdthesis and masterthesis and then the philosophy behind is that it is trying to match against few defined `entry type` and when it fails to do that it chooses `misc` by default.

Our goal there was simple to replace the old `bfe_bibtex`, as it wasn't working for us - each record had the same `entry type`.

**Comment by kaplun** [comment]
Seems to me that Zenodo, CDS, INSPIRE all went into different directions in the support for BibTeX. Of course this depends very much on each having a different datamodel and focusing of slightly different document types.

At this stage, what shall we do? Is there some help coming from Jinja2 so that we can nicely create mapping from JSONAlchemy to BibTeX (with Jinja2 helping in all the escaping businness)?

Other proposals?

**Comment by aw-bib** [comment]
We could check into join2 implementation of this (long on my list), probably some generic ideas can be used.

**Comment by lnielsen** [comment]
Just my few cents: As mentioned by others the BibTeX export is highly dependent on data model and each particular record (e.g if a journal article is missing some information it might not classify as ``@article`` but ``@misc`` instead). 

What is common I think is that all need serialisation of an abstract BibTeX data model. So it would be helpful if you in Invenio provided tools to easily build an a abstract BibTeX tree, and then serialise that tree into BibTeX.

**Comment by aw-bib** [comment]
@lnielsen: I'm not sure that you should classify a journal article due to missing fields as `@misc`. I'd definitely treat it as `@article` with missing fields.

**Comment by kaplun** [comment]
@aw-bib what Lars means it is that how we map to BibTeX is highly dependent on each Invenio instance. 
So the best we can do, indeed, is to have each Invenio instance to map metadata to an abstract pythonic BibTeX representation, and then delegating to some specialized BibTeX library to actual serialize the data into a BibTeX output (taking care of all brackets, accents, etc.).

**Comment by lnielsen** [comment]
@kaplun Yep, that's correct.

@aw-bib: I just meant to point out a generic non-trivial issue with BibTeX generation using ``@article`` as example. E.g. the BibTeX entry type ``@article`` have a list of required fields (``author``, ``title``, ``journal``, ``year``, ``volume``) and optional fields (``number``, ``pages``, ``month``, ``note``, ``key``). See http://en.wikipedia.org/wiki/BibTeX under "Entry types". If you create an ``@article`` type without say ``volume`` (a required field), and you run it through BibTeX it will spit out an error/warning - i.e. the generated BibTeX is not fully valid. I had users politely "complaining" about this ;-). ``@article`` might be a bad example, but it goes for all the other entry types as well, that they have required and optional fields, and if you are missing a required field in the BibTeX output, then it is not valid output and BibTeX will complain.

**Comment by aw-bib** [comment]
@lnielsen: Understood bibtex. And I agree: it spits out a warning. But formatting a journal article without volume as `@misc` would get rid you of the warning and give you a broken bibliography. So, if the record in question is an `@article` it should be `@article` regardless if the record contains all mandatory fields. Cataloguing should suggest/encourage/ensure/enforce to get all fields during ingestion, but even if they're not there you should get a warning that they are not there and not just work through without notification. (Probably, this is a philosophical question, but I don't think so.)

BTW: we handle it in join2 by modelling our document types by means of `3367_` where we store our document type (we have more than `bibtex` or EndNote, Citavi, Zotero, [what have you] can handle) and also add the proper mapping there (type is one of our authority thingy). This looks like:

    3367_ $0PUB:(DE-HGF)16
          $2PUB:(DE-HGF)
          $aJournal Article
    3367_ $00
          $2EndNote
          $aJournal Article
    3367_ $2DRIVER
         $aarticle
    3367_ $2BibTeX
          $aARTICLE

And then you're at a quite generic level of mapping if your Marc is right.

**Comment by lnielsen** [comment]
@aw-bib: Again, ``@article`` might be a bad example in this context. Take some of the other entry types and you have the same issue. Nonetheless I've still had several end-users (researchers) which uses the generated BibTeX to format their bibliography complain exactly about this issue.

> Cataloguing should suggest/encourage/ensure/enforce to get all fields during ingestion, but even if they're not there you should get a warning that they are not there and not just work through without notification. (Probably, this is a philosophical question, but I don't think so.)

You should have as much metadata as possible and check and fix problems in it, agreed in principle. However, it can be a very expensive in terms of cataloging/developer man-power and depends on use cases. E.g. Zenodo is primarily relying on end-users providing the metadata. 

I think your point underlines that the fact that BibTeX formatting is highly dependent on the service it is running on, and thus why I suggested providing the toolbox + very simple defaults to 1) make it as easy as possible to have bibtex export in Invenio and 2) not try to solve every possible problem that can happen when you map an instance's data model to BibTeX.

**Comment by aw-bib** [comment]
@lnielsen I see your point, but I think you fix it at the wrong place. IMHO it's just not working to derive document types from the existing data correctly. 

I look at it the other way around. You get a user submission. (This is the same here. No cataloguers no developers. Joe Doe is submitting.) Now, if I as a user select "journal article" as document type, I, as a user, would expect that the record in question is formatted as `@article` in bibtex and not as `@misc` simply cause I did not add the volume yet. (Probably, it's "ahead of print" stuff.) Sure, bibtex will issue a warning (no error, btw.) but well, this is to be expected and it is even ok. I get a journal reference with a missing field. But better than getting no journal reference at all as in `@misc`...

IMHO this holds for all other document types as well.

> You should have as much metadata as possible and check and fix problems in it, agreed in principle. However, it can be a very expensive in terms of cataloging/developer man-power and depends on use cases.

I do _not_ think about manual curation after submission. 

Usually, you have to rely on what the users submits. Perfectly agree. Also agreed that this might be crap. Still, I would expect the submission interface that it tells me as the user what fields would be necessary for the document type chosen to be a complete reference. Ie. that an article submission signifies that you have to add the journal. So make it bold an red or whatever.

It's an _other_ question whether it just marks the field or whether you're enforcing it's input and completely unrelated to whether you have manpower for curation down the road. Depending on your installation you might choose either one. Again perfectly agreed. At join2 actually we have both: for internal records we signify that journal is a "must have" for articles but we don't enforce it. For records that get some upstream formal curation and end up in the bean counting of our instiutions you have to add the journal and we don't accept the record for submission unless you do so. Still both records would get formatted as `@article` as the user chose them to be journal articles. Ie. the bioprocessor on layer 8 told us to do so.

In your sense bibtex export in the first case would be broken cause it issues a warning. I take this as a feature: it tells me, probably much later, that I missed to add the journal. Formatting as `@misc` will not notify me and I'll have to scan and compare my bibliography manually and check in each case if it shouldn't have a journal entry. 

I think this very same logic holds for all document types, as all that the document type signifies is the list of mandatory fields. Mandatory in the sense of the ability to produce a correct citation while correct itself is defined as "this item is retrievable and the display follows conventions for this". Ok, one could drop all the text clutter and just cite the DOI right away, would save a lot of space, perfectly agreed. Just doesn't yet follow the conventions.

Thus I think the bibtex export like all other bibliographic exports is not so dependent on your instance or use case.

**Comment by lnielsen** [comment]
> Now, if I as a user select "journal article" as document type, I, as a user, would expect that the record in question is formatted as @article in bibtex and not as @misc simply cause I did not add the volume yet.

I can only say that my users disagrees with you. We continuously had support requests on this issue until we fixed it, and reverse, we haven't had any support requests that complained about using ``@misc`` instead of ``@article`` after we fixed it. I naturally can't say if we'll get any requests in the future.

> Thus I think the bibtex export like all other bibliographic exports is not so dependent on your instance or use case.

I think we can agree to disagree on the issue then :-)

**Comment by aw-bib** [comment]
yepp, I fear we agree that we disagree.

Concerning your requests, I think I wouldn't file one if you format journal article as misc simply cause "this is so far of, this export just doesn't work." :(

**Comment by tiborsimko** [comment]
> Sure, bibtex will issue a warning (no error, btw.)

Perhaps those users that use permissive tool chain see a warning and don't complain, while those users that use restrictive tool chain see an error and complain :smile: 

I'm mentioning this because you can find several sources on the web saying that `volume` is optional, not mandatory, for `@article`.  This contradicts the [wikipedia entry](http://en.wikipedia.org/wiki/BibTeX) cited by @lnielsen.  And, as far as I'm concerned, it makes more sense to me for `volume` to be optional, as this nicely covers the "submitted-to" paper scenario, where the volume may not be known until the paper is published several months later.

For additional insight, let me quote from the "BibTeXing" 1988 guide by Oren Patashnik himself:

- **article** An article from a journal or magazine. Required fields: author, title, journal, year. Optional fields: volume, number, pages, month, note.

(You can find this guide somewhere under ` /usr/share/doc/texlive-doc/bibtex/base/btxdoc.pdf` in your TeX installation.)

I therefore agree with @aw-bib that `volume` is really an optional field that does not justify switching `@article` type to `@misc` in our BibTeX output.  (While missing `journal` would be another matter.)

Anyway, this discussion just shows that each site may want to configure their TeX output to follow the habits of their user community and perhaps their prevalent tool chain.  Invenio-wise, we can come with good defaults in our demo site, following standards as closely as possible, all the while offering easily configurable/extendible hooks, letting admins to tweak the output further if they wish.  (E.g. consider where to store URLs and abstracts and stuff that the standard does not mention.  We may follow majority usage in our subject domain, but this won't necessarily suit everybody.)

**Comment by aw-bib** [comment]
@tiborsimko you may be right about permissiveness of the toolchain. But I think this is sort of second order, as it is only a technical issue.

For the "submitted-to" scenario people actually enter e.g. `-` in case we enforce the field (e.g. http://juser.fz-juelich.de/record/188781) I admit, that I don't think this is perfect and I'd rather have a better solution but it's simple and works surprisingly well.

Anyway, I think the main difference on handling exports here is that in join2 repos we prefer to trust the _user_  and use the type supplied upon submission _all the time_ in favour of trying to be clever. 

Many of our records have actually more than one type. Thesis + Report is quite obvious, Thesis + Book as well but also proceedings published in a journal e.g. This is intended as otherwise we'd not have some 35 document types, but way more to cover all those natural double types. Guessing gets a bit wild here. From this comes the procedure that if a Thesis + Book is submitted _as Thesis_ we export it as `@phdthesis` while if it is submitted as book we export it as `@book`. It's in the eye of the beholder what is her preference. E.g. a philosopher would more likely talk about "her first book" than a physicist, who would more likely call it his phd (never heard one talking about "her book" there). We believe that by trusting the submitters choice we are closest to the eventual users community.

**Comment by lnielsen** [comment]
> I therefore agree with @aw-bib that volume is really an optional field that does not justify switching @article type to @misc in our BibTeX output. (While missing journal would be another matter.)

I've mentioned above that ``@article`` is a bad example because I think it side tracks the conversation. What we are talking about is the existence of **required** vs **optional** fields in BibTeX and that **missing** required fields in out is producing errors.

> Concerning your requests, I think I wouldn't file one if you format journal article as misc simply cause "this is so far of, this export just doesn't work." :(

And why wouldn't my other users say the same about the reverse? "The service can't generate proper BibTeX output which doesn't generate errors. This is so far of that I just don't want to bother". (i.e. I don't agree with your argument).

**Comment by aw-bib** [comment]
See your point about the errors @lnielsen, if a missing volume would throw an error and break compilation. Usually, it's just a warning so it's not that bad. Why wouldn't I file issues? I'd have to check all doctypes in export, add missing fields, cross check, most likely in this case I'll be faster to do it myself than export first and fix it up. (IOW: you'd loose me very fast on this. To fast to file issues. But that's just a guess.)

But as I say: the main issue is not a document type or whatever but who defines the document type for export.

We use the users input decision, your procedure prefer to use existing metadata and guess what it could be. We prefer to warn the user if input is missing, you prefer not to and get clean compilation on output.

Both are valid procedures in a sense.

If I look at what you do for submission to Zenodo I see why you do the guessing. Your type _Publication_ is almost everything (interesting that you split of poster and presentation, BTW), so your submission just don't ask the user what it is, and thus you don't even stand a chance to tell which fields should be filled in. (Actually, I still believe that this is the only reason to have document types at all.) So, at Zenodo AFAIS I can fill in all journal fields, all book fields, all theses fields and all conference fields for one single publication or I can also leave everything blank even for the mentioned proceedings paper published in a journal. So indeed you'll end up with a lot of `@misc`, I guess. E.g. 16697 says "book section" and instead of `@inbook` it gets `@misc`. 16696 says journal article and again gets `@misc`, while 16694 says journal article and gets `@article` and so on. This would indeed be (unusable) inconsistent in _our_ world which has to produce the scientific report at the end of the day with a proper bibliography. Zenodo doesn't want to do that, however. (BTW: I think if it displays journal article as a badge it should export `@article` or display misc on the badge as well to get consistent. At the moment two different guesses get different results. Probably a ticket for Zenodo?)

So, I admit, having these extremes you're right: you can't do it via a general export and every instance will forever end up with needing programmers to adopt source code.

**Comment by Eothred** [comment]
Cool to see that my reported issue is still being worked on several years later, I had no idea :)

Thought I'd point out that perhaps you may find some inspiration/ideas/solutions also by looking at how desktop applications such as [BibDesk](http://sourceforge.net/projects/bibdesk/) and [KBibtex](http://home.gna.org/kbibtex/) deal with similar issues.

**Comment by jirikuncar** [comment]
### Proposal

**Step 1**

+ customizable type detection
  - custom field in record metadata
  - collection definition
  - non-empty required fields

**Step 2**

+ mappings (JSON-to-JSON) for generating BibTeX based on detected/given type

**Step 3**

+ simple rendering
  - optional caching

--
http://nwalsh.com/tex/texhelp/bibtx-7.html

**Comment by kaplun** [comment]
BibTeX export is data-model specific, hence solved in each service overlay.

See e.g. an implementation from INSPIRE: 
* serializer: https://github.com/inspirehep/inspire-next/blob/8c2ac6993011ae8cd455aec3b97e7598c1be1be2/inspirehep/modules/records/serializers/bibtex_serializer.py
* actual implementation: https://github.com/inspirehep/inspire-next/blob/8c2ac6993011ae8cd455aec3b97e7598c1be1be2/inspirehep/utils/bibtex.py
