### ISSUE TITLE
INSPIRE INST An Institution Publication Profile Page

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#697]
Originally by *hoc* on 2011-06-22

It would be nice to Have an Institution Publication Profile page 
analogous to: http://inspirebeta.net/author/G.Dixon.1 With a list of 
the top authors from the institution, co-authoring institutions, 
etc...

**Comment by jirikuncar** [comment]
@glouppe is there any plan to include *institution* pages while working on *author* pages?

**Comment by glouppe** [comment]
While working on authors, not directly.

But this is clearly something we will do eventually within Inspire. Once the author logic will be implemented, having similar mechanisms for institutions should be straightforward.

**Comment by lnielsen** [comment]
Should we move the issue to Inspire?

**Comment by jirikuncar** [comment]
It's fine here. We can create new 'institutions' module similar to 'authors' that can be enabled/disabled independently.

**Comment by tiborsimko** [comment]
We already have this in Invenio by means of the authority records.  Check `/collection/Institutes` page on the Invenio demo site.  The institute page shows preceding institutes, superseeding institutes, and the list of dependent records.  The display can be modified via formatting templates to suit each concrete installation. I'm therefore closing this issue here in Invenio.
