### ISSUE TITLE
RFC search: introduce new operator => (inclusive "date after" search)

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#755]
Originally by *annetteh* on 2011-07-22

The search "date after year1" does not exclude year1.
"fin a ellis and date > 2009" gives the same result as "author:ellis date:2009->2011"

**Comment by jirikuncar** [comment]
> Introduce new operator `=>` (https://github.com/inveniosoftware/invenio/issues/755#issuecomment-41852677)

@tiborsimko @jalavik shall we make an RFC from this issue?

**Comment by tiborsimko** [comment]
@jirikuncar We can transform this very issue into an RFC here?  Saves electrons :)

Some quick thoughts from me:

- If "date after" is the only use case, then I like Heath's proposal for "2000+", since it would preserve the behaviour of the good old arrow operator, and people are used to type N+ for citation count queries or author count queries already.
- If there are some use case for non-numeric alphabetic queries (e.g. "subject:hep->iii"), then we should ponder how these would read with inclusive/exclusive operators.
- Depending on the wanted milestone, we can take inspiration from Elasticsearch syntax here?

**Comment by jirikuncar** [comment]
- `updated:<=2015-01-01`
- `numberofauthors:>100`

**Comment by kaplun** [comment]
:+1:

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-query-parser #58](https://github.com/inveniosoftware/invenio-query-parser/issues/58) via [**ZenHub**](https://www.zenhub.com/)
